import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadPlanningStageStartedPayload as ContractsThreadPlanningStageStartedPayloadSchema,
  ThreadPlanningPrdCreatedPayload as ContractsThreadPlanningPrdCreatedPayloadSchema,
  ThreadPlanningIssuesCreatedPayload as ContractsThreadPlanningIssuesCreatedPayloadSchema,
  ThreadPlanningIssuesRevisedPayload as ContractsThreadPlanningIssuesRevisedPayloadSchema,
  ThreadPlanningIssueReviewRequestedPayload as ContractsThreadPlanningIssueReviewRequestedPayloadSchema,
  ThreadPlanningPrdBundleLoadedPayload as ContractsThreadPlanningPrdBundleLoadedPayloadSchema,
  ThreadPlanningWorkflowStageSetPayload as ContractsThreadPlanningWorkflowStageSetPayloadSchema,
  ThreadImplementationRunLaunchedPayload as ContractsThreadImplementationRunLaunchedPayloadSchema,
  ThreadImplementationRunUpdatedPayload as ContractsThreadImplementationRunUpdatedPayloadSchema,
  ThreadImplementationChangeRequestRetryRequestedPayload as ContractsThreadImplementationChangeRequestRetryRequestedPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadDevReviewCreatedPayload as ContractsThreadDevReviewCreatedPayloadSchema,
  ThreadDevReviewReplayMetadataUpdatedPayload as ContractsThreadDevReviewReplayMetadataUpdatedPayloadSchema,
  ThreadDevReviewUpdatedPayload as ContractsThreadDevReviewUpdatedPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadPlanningStageStartedPayload = ContractsThreadPlanningStageStartedPayloadSchema;
export const ThreadPlanningPrdCreatedPayload = ContractsThreadPlanningPrdCreatedPayloadSchema;
export const ThreadPlanningIssuesCreatedPayload = ContractsThreadPlanningIssuesCreatedPayloadSchema;
export const ThreadPlanningIssuesRevisedPayload = ContractsThreadPlanningIssuesRevisedPayloadSchema;
export const ThreadPlanningIssueReviewRequestedPayload =
  ContractsThreadPlanningIssueReviewRequestedPayloadSchema;
export const ThreadPlanningPrdBundleLoadedPayload =
  ContractsThreadPlanningPrdBundleLoadedPayloadSchema;
export const ThreadPlanningWorkflowStageSetPayload =
  ContractsThreadPlanningWorkflowStageSetPayloadSchema;
export const ThreadImplementationRunLaunchedPayload =
  ContractsThreadImplementationRunLaunchedPayloadSchema;
export const ThreadImplementationRunUpdatedPayload =
  ContractsThreadImplementationRunUpdatedPayloadSchema;
export const ThreadImplementationChangeRequestRetryRequestedPayload =
  ContractsThreadImplementationChangeRequestRetryRequestedPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadDevReviewCreatedPayload = ContractsThreadDevReviewCreatedPayloadSchema;
export const ThreadDevReviewUpdatedPayload = ContractsThreadDevReviewUpdatedPayloadSchema;
export const ThreadDevReviewReplayMetadataUpdatedPayload =
  ContractsThreadDevReviewReplayMetadataUpdatedPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
