import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadWorkflowStepModelSetPayload as ContractsThreadWorkflowStepModelSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadComposerModeSetPayload as ContractsThreadComposerModeSetPayloadSchema,
  ThreadPlanningStageStartedPayload as ContractsThreadPlanningStageStartedPayloadSchema,
  ThreadPlanningSpecCreatedPayload as ContractsThreadPlanningSpecCreatedPayloadSchema,
  ThreadPlanningTicketsCreatedPayload as ContractsThreadPlanningTicketsCreatedPayloadSchema,
  ThreadPlanningTicketsRevisedPayload as ContractsThreadPlanningTicketsRevisedPayloadSchema,
  ThreadPlanningTicketReviewRequestedPayload as ContractsThreadPlanningTicketReviewRequestedPayloadSchema,
  ThreadPlanningSpecBundleLoadedPayload as ContractsThreadPlanningSpecBundleLoadedPayloadSchema,
  ThreadPlanningWorkflowStageSetPayload as ContractsThreadPlanningWorkflowStageSetPayloadSchema,
  ThreadImplementationRunLaunchedPayload as ContractsThreadImplementationRunLaunchedPayloadSchema,
  ThreadImplementationRunUpdatedPayload as ContractsThreadImplementationRunUpdatedPayloadSchema,
  ThreadImplementationRunCancelRequestedPayload as ContractsThreadImplementationRunCancelRequestedPayloadSchema,
  ThreadImplementationChangeRequestRetryRequestedPayload as ContractsThreadImplementationChangeRequestRetryRequestedPayloadSchema,
  ThreadAppReviewWorkflowLaunchedPayload as ContractsThreadAppReviewWorkflowLaunchedPayloadSchema,
  ThreadAppReviewWorkflowUpdatedPayload as ContractsThreadAppReviewWorkflowUpdatedPayloadSchema,
  ThreadAppReviewWorkflowCancelRequestedPayload as ContractsThreadAppReviewWorkflowCancelRequestedPayloadSchema,
  ThreadAppReviewWorkflowResumeRequestedPayload as ContractsThreadAppReviewWorkflowResumeRequestedPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadPinnedPayload as ContractsThreadPinnedPayloadSchema,
  ThreadUnpinnedPayload as ContractsThreadUnpinnedPayloadSchema,
  ThreadPinReorderedPayload as ContractsThreadPinReorderedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadAppReviewCreatedPayload as ContractsThreadAppReviewCreatedPayloadSchema,
  ThreadAppReviewEvidenceUpdatedPayload as ContractsThreadAppReviewEvidenceUpdatedPayloadSchema,
  ThreadAppReviewUpdatedPayload as ContractsThreadAppReviewUpdatedPayloadSchema,
  ThreadWorkflowSubagentBatchCreatedPayload as ContractsThreadWorkflowSubagentBatchCreatedPayloadSchema,
  ThreadWorkflowSubagentBatchChildUpdatedPayload as ContractsThreadWorkflowSubagentBatchChildUpdatedPayloadSchema,
  ThreadWorkflowSubagentBatchCompletedPayload as ContractsThreadWorkflowSubagentBatchCompletedPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadWorkflowStepModelSetPayload = ContractsThreadWorkflowStepModelSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadComposerModeSetPayload = ContractsThreadComposerModeSetPayloadSchema;
export const ThreadPlanningStageStartedPayload = ContractsThreadPlanningStageStartedPayloadSchema;
export const ThreadPlanningSpecCreatedPayload = ContractsThreadPlanningSpecCreatedPayloadSchema;
export const ThreadPlanningTicketsCreatedPayload =
  ContractsThreadPlanningTicketsCreatedPayloadSchema;
export const ThreadPlanningTicketsRevisedPayload =
  ContractsThreadPlanningTicketsRevisedPayloadSchema;
export const ThreadPlanningTicketReviewRequestedPayload =
  ContractsThreadPlanningTicketReviewRequestedPayloadSchema;
export const ThreadPlanningSpecBundleLoadedPayload =
  ContractsThreadPlanningSpecBundleLoadedPayloadSchema;
export const ThreadPlanningWorkflowStageSetPayload =
  ContractsThreadPlanningWorkflowStageSetPayloadSchema;
export const ThreadImplementationRunLaunchedPayload =
  ContractsThreadImplementationRunLaunchedPayloadSchema;
export const ThreadImplementationRunUpdatedPayload =
  ContractsThreadImplementationRunUpdatedPayloadSchema;
export const ThreadImplementationRunCancelRequestedPayload =
  ContractsThreadImplementationRunCancelRequestedPayloadSchema;
export const ThreadImplementationChangeRequestRetryRequestedPayload =
  ContractsThreadImplementationChangeRequestRetryRequestedPayloadSchema;
export const ThreadAppReviewWorkflowLaunchedPayload =
  ContractsThreadAppReviewWorkflowLaunchedPayloadSchema;
export const ThreadAppReviewWorkflowUpdatedPayload =
  ContractsThreadAppReviewWorkflowUpdatedPayloadSchema;
export const ThreadAppReviewWorkflowCancelRequestedPayload =
  ContractsThreadAppReviewWorkflowCancelRequestedPayloadSchema;
export const ThreadAppReviewWorkflowResumeRequestedPayload =
  ContractsThreadAppReviewWorkflowResumeRequestedPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;
export const ThreadPinnedPayload = ContractsThreadPinnedPayloadSchema;
export const ThreadUnpinnedPayload = ContractsThreadUnpinnedPayloadSchema;
export const ThreadPinReorderedPayload = ContractsThreadPinReorderedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadAppReviewCreatedPayload = ContractsThreadAppReviewCreatedPayloadSchema;
export const ThreadAppReviewUpdatedPayload = ContractsThreadAppReviewUpdatedPayloadSchema;
export const ThreadAppReviewEvidenceUpdatedPayload =
  ContractsThreadAppReviewEvidenceUpdatedPayloadSchema;
export const ThreadWorkflowSubagentBatchCreatedPayload =
  ContractsThreadWorkflowSubagentBatchCreatedPayloadSchema;
export const ThreadWorkflowSubagentBatchChildUpdatedPayload =
  ContractsThreadWorkflowSubagentBatchChildUpdatedPayloadSchema;
export const ThreadWorkflowSubagentBatchCompletedPayload =
  ContractsThreadWorkflowSubagentBatchCompletedPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
